oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","ruSelectAccidentTow, ruTowingBySriTow," +
 "ruSriTowAndMacRepair,ruActivateV1");
oprMgt.addRegulationUnitsToProcessRegulationPolicy("HappyTours","HappyToursP1","ruTowingBySwiftTow,ruSwiftTowAndMacRepair,
ruActivateV2");
oprMgt.removeRegulationUnit("ruSelectAccidentTow");
oprMgt.removeRegulationUnit("ruTowingBySriTow");
oprMgt.removeRegulationUnit("ruSriTowAndMacRepair");
orgMgt.removeRole("LF2");
orgMgt.removeRole("TC5");
orgMgt.updateTask("SC","PayLF","outputs", "remove","LF2.payLegalAid.Res");
orgMgt.updateTask("SC","PayLF","inputs", "remove","LF2.payLegalAid.Req");
orgMgt.updateTask("SC","Analyze","remove","outputs","SC-TC5.orderTow.Req,SC-LF2.inspectAccident.Req");
orgMgt.updateTask("GC1","OrderRepair","remove","inputs","SC-GC1.orderRepair.Req");
orgMgt.removeContract("SC-LF2");
orgMgt.removeContract("LF2-TC5");
orgMgt.removeContract("GC1-TC5");
orgMgt.removeContract("SC-TC5");
orgMgt.removeBehaviorUnit("bTowingBySriTow");
orgMgt.addBehaviorUnitToProcess("HappyTours","HappyToursP1","bTowingBySwiftTow");
orgMgt.removeBehaviorUnitFromProcess("HappyTours","HappyToursP1","bTowingBySriTow");
oprMgt.removeSynchronizationRule("SC","payTC5");
oprMgt.removeSynchronizationRule("SC","payLF2");
oprMgt.removeSynchronizationRule("GC1","doRepairV3");
oprMgt.removeRoutingRule("GC1","orderRepairResponseV3");
oprMgt.removeRoutingRule("SC","analyzeResponseV11");
oprMgt.removeRoutingRule("SC","analyzeResponseV12");
oprMgt.removeRoutingRule("SC","payLFResponse2");
oprMgt.removeRoutingRule("SC","ruSelectAccidentTow");