global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage
import au.edu.swin.ict.road.common.StateRecord
import au.edu.swin.ict.road.common.Weight;
import au.edu.swin.ict.road.common.VSN;
import au.edu.swin.ict.road.common.ProcessManagementState;
rule "rAdmissionCheck"
  when
   $msg : RoleServiceMessage(operationName== "assist", state=="admittable")
  then
   actions.AdmissionControl("assist","<<limit>>,20000",$msg);
   update($msg);
end
rule "rProcessSelection"
  when
   $msg : RoleServiceMessage(operationName== "assist", state=="Routable")
  then
   actions.LoadBalance("assist","<<lbConfig>>",$msg);
   update($msg);
end