global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "assessRepairResponse"
  when
   $msg : RoleServiceMessage(operationName== "assessRepairResponse", state=="forwardable")
  then
   actions.Forward("AS-GC2.reportAssessment.Req","reportAssessment.xsl",$msg);
   actions.Forward("AS-SC.payAssessment.Req","payAssessment.xsl",$msg);
end