global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "assessRepairTC1"
  when
   $e1 : EventRecord(eventId == "eAssessRepairReqByTC1")
  then
   disabledSet.disable("assessRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"TC1-AS.assessRepair.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"assessRepair.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end

rule "assessRepairTC2"
  when
   $e1 : EventRecord(eventId == "eAssessRepairReqByTC2")
  then
   disabledSet.disable("assessRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"TC2-AS.assessRepair.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"assessRepair.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end