global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;

rule "startRepairMonitor3d"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==true)
    then
		actions.publishEvent("eDeliveredVehicleToGC1ByTC1",$msg);
end

rule "startRepairMonitor2d"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==true)
    then
		actions.publishEvent("eDeliveredVehicleToGC1ByTC1",$msg);
end

rule "startRepairMonitor4d"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==true)
    then
		actions.publishEvent("eDeliveredVehicleToGC1ByTC1",$msg);
end