global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "orderRoom"
  when
   $e1 : EventRecord(eventId == "eOrderRoomReqd")
  then
   disabledSet.disable("orderRoom");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-HC2.orderRoom.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRoom.xsl","OrderRoom");
   actions.ExecuteTask(exMsg);
end