global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "pickUpMonitor3h"
    when
		$msg : MessageReceivedEvent(operationName == "pickUp",  response ==false)
    then
		actions.publishEvent("ePickUpReqd",$msg);
end
rule "pickUpMonitor4h"
    when
		$msg : MessageReceivedEvent(operationName == "pickUp",  response ==false)
    then
		actions.publishEvent("ePickUpReqd",$msg);
end