global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "orderTow"
    when
		$msg : MessageReceivedEvent(operationName == "orderTow", response ==false)//, isResponse==false
    then
		actions.publishEvent("eTowReqdFromTC5",$msg);
end

rule "payTow"
    when
		$msg : MessageReceivedEvent(operationName == "payTow" , response==false)
    then
		actions.publishEvent("ePayT5Reqd",$msg);
end

rule "payTowResponse"
    when
		$msg : MessageReceivedEvent(operationName == "payTow", response==true)
    then
		actions.publishEvent("eTC5Paid",$msg);
end