global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "analyzeResponseV10" salience 1
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
  //if accident tow  and tell to reexecute rules
   actions.AlterPath("ruTowingByTowTow,ruTomTowAndMacRepair","ruTowingByMarkTow,ruMarkTowAndMacRepair",$msg);
end