global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "towResponse"
  when
   $msg : RoleServiceMessage(operationName== "towResponse", state=="forwardable")
  then
   actions.Forward("SC-TC5.payTow.Req","PayTC5Req.xsl",$msg);
end

rule "towResponseV2"
  when
   $msg : RoleServiceMessage(operationName== "towResponse", state=="forwardable")
  then
   actions.Forward("GC1-TC5.sendGCLocation.Res","SendGC1LocationResFromTC5.xsl",$msg);
end