global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "tow"
  when
   EventRecord(eventId == "eTowReqdFromTC5") and  EventRecord(eventId == "eSentGC1LocToTC5") and EventRecord(eventId == "eAuthorizedTow")
  then
   disabledSet.disable("tow");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TC5.orderTow.Req","GC1-TC5.sendGCLocation.Req","LF2-TC5.authorizeTow.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"TowTC5.xsl","Tow");
   actions.ExecuteTask(exMsg);
end