global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.composite.regulation.DisabledRuleSet disabledSet;
import au.edu.swin.ict.serendip.event.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "tow"
  when
   EventRecord(eventId == "TowReqd") and  EventRecord(eventId == "GC2LocKnown")
  then
   disabledSet.disable("tow");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TC2.orderTow.Req","GC2-TC2.sendGCLocation.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"TowTC2.xsl","Tow");
   actions.ExecuteTask(exMsg);
end