//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ContractType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ContractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Types">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Monitor" type="{http://www.swin.edu.au/ict/road/monitor}MonitorType" minOccurs="0"/>
 *         &lt;element name="LinkedFacts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/contract}ContractLinkedFactType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AbstractContract" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Terms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Term" type="{http://www.swin.edu.au/ict/road/term}TermType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Monitors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Monitor" type="{http://www.swin.edu.au/ict/road/monitor}MonitorRoleType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RoleAID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RoleBID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="passthrough" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractType", namespace = "http://www.swin.edu.au/ict/road/contract", propOrder = {
        "types",
        "monitor",
        "linkedFacts",
        "abstractContract",
        "state",
        "terms",
        "monitors",
        "roleAID",
        "roleBID",
        "description"
})
public class ContractType {

    @XmlElement(name = "Types", namespace = "", required = true)
    protected ContractType.Types types;
    @XmlElement(name = "Monitor", namespace = "")
    protected MonitorType monitor;
    @XmlElement(name = "LinkedFacts", namespace = "")
    protected ContractType.LinkedFacts linkedFacts;
    @XmlElement(name = "AbstractContract", namespace = "")
    protected Boolean abstractContract;
    @XmlElement(name = "State", namespace = "")
    protected String state;
    @XmlElement(name = "Terms", namespace = "")
    protected ContractType.Terms terms;
    @XmlElement(name = "Monitors", namespace = "")
    protected ContractType.Monitors monitors;
    @XmlElement(name = "RoleAID", namespace = "", required = true)
    protected String roleAID;
    @XmlElement(name = "RoleBID", namespace = "", required = true)
    protected String roleBID;
    @XmlElement(name = "Description", namespace = "")
    protected String description;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "passthrough", required = true)
    protected String passthrough;

    /**
     * Gets the value of the types property.
     *
     * @return possible object is
     * {@link ContractType.Types }
     */
    public ContractType.Types getTypes() {
        return types;
    }

    /**
     * Sets the value of the types property.
     *
     * @param value allowed object is
     *              {@link ContractType.Types }
     */
    public void setTypes(ContractType.Types value) {
        this.types = value;
    }

    /**
     * Gets the value of the monitor property.
     *
     * @return possible object is
     * {@link MonitorType }
     */
    public MonitorType getMonitor() {
        return monitor;
    }

    /**
     * Sets the value of the monitor property.
     *
     * @param value allowed object is
     *              {@link MonitorType }
     */
    public void setMonitor(MonitorType value) {
        this.monitor = value;
    }

    /**
     * Gets the value of the linkedFacts property.
     *
     * @return possible object is
     * {@link ContractType.LinkedFacts }
     */
    public ContractType.LinkedFacts getLinkedFacts() {
        return linkedFacts;
    }

    /**
     * Sets the value of the linkedFacts property.
     *
     * @param value allowed object is
     *              {@link ContractType.LinkedFacts }
     */
    public void setLinkedFacts(ContractType.LinkedFacts value) {
        this.linkedFacts = value;
    }

    /**
     * Gets the value of the abstractContract property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isAbstract() {
        if (abstractContract == null) {
            return false;
        }
        return abstractContract;
    }

    /**
     * Sets the value of the abstractContract property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setAbstract(Boolean value) {
        this.abstractContract = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the terms property.
     *
     * @return possible object is
     * {@link ContractType.Terms }
     */
    public ContractType.Terms getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     *
     * @param value allowed object is
     *              {@link ContractType.Terms }
     */
    public void setTerms(ContractType.Terms value) {
        this.terms = value;
    }

    /**
     * Gets the value of the monitors property.
     *
     * @return possible object is
     * {@link ContractType.Monitors }
     */
    public ContractType.Monitors getMonitors() {
        return monitors;
    }

    /**
     * Sets the value of the monitors property.
     *
     * @param value allowed object is
     *              {@link ContractType.Monitors }
     */
    public void setMonitors(ContractType.Monitors value) {
        this.monitors = value;
    }

    /**
     * Gets the value of the roleAID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoleAID() {
        return roleAID;
    }

    /**
     * Sets the value of the roleAID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoleAID(String value) {
        this.roleAID = value;
    }

    /**
     * Gets the value of the roleBID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoleBID() {
        return roleBID;
    }

    /**
     * Sets the value of the roleBID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoleBID(String value) {
        this.roleBID = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the passthrough property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPassthrough() {
        return passthrough;
    }

    /**
     * Sets the value of the passthrough property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPassthrough(String value) {
        this.passthrough = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/contract}ContractLinkedFactType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "fact"
    })
    public static class LinkedFacts {

        @XmlElement(name = "Fact", namespace = "", required = true)
        protected List<ContractLinkedFactType> fact;

        /**
         * Gets the value of the fact property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fact property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFact().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link ContractLinkedFactType }
         */
        public List<ContractLinkedFactType> getFact() {
            if (fact == null) {
                fact = new ArrayList<ContractLinkedFactType>();
            }
            return this.fact;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Monitor" type="{http://www.swin.edu.au/ict/road/monitor}MonitorRoleType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "monitor"
    })
    public static class Monitors {

        @XmlElement(name = "Monitor", namespace = "")
        protected List<MonitorRoleType> monitor;

        /**
         * Gets the value of the monitor property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the monitor property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMonitor().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MonitorRoleType }
         */
        public List<MonitorRoleType> getMonitor() {
            if (monitor == null) {
                monitor = new ArrayList<MonitorRoleType>();
            }
            return this.monitor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Term" type="{http://www.swin.edu.au/ict/road/term}TermType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "term"
    })
    public static class Terms {

        @XmlElement(name = "Term", namespace = "")
        protected List<TermType> term;

        /**
         * Gets the value of the term property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the term property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTerm().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link TermType }
         */
        public List<TermType> getTerm() {
            if (term == null) {
                term = new ArrayList<TermType>();
            }
            return this.term;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "any"
    })
    public static class Types {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         *
         * @return possible object is
         * {@link Object }
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         *
         * @param value allowed object is
         *              {@link Object }
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }

}
