//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MonitorType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="MonitorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event" type="{http://www.swin.edu.au/ict/road/monitor}MonitorEventType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fact" type="{http://www.swin.edu.au/ict/road/monitor}FactRefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="analysis" type="{http://www.swin.edu.au/ict/road/monitor}AnalysisType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitorType", namespace = "http://www.swin.edu.au/ict/road/monitor", propOrder = {
        "event",
        "fact",
        "analysis"
})
public class MonitorType {

    @XmlElement(namespace = "")
    protected List<MonitorEventType> event;
    @XmlElement(namespace = "")
    protected List<FactRefType> fact;
    @XmlElement(namespace = "", required = true)
    protected AnalysisType analysis;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the event property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link MonitorEventType }
     */
    public List<MonitorEventType> getEvent() {
        if (event == null) {
            event = new ArrayList<MonitorEventType>();
        }
        return this.event;
    }

    /**
     * Gets the value of the fact property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fact property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFact().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link FactRefType }
     */
    public List<FactRefType> getFact() {
        if (fact == null) {
            fact = new ArrayList<FactRefType>();
        }
        return this.fact;
    }

    /**
     * Gets the value of the analysis property.
     *
     * @return possible object is
     * {@link AnalysisType }
     */
    public AnalysisType getAnalysis() {
        return analysis;
    }

    /**
     * Sets the value of the analysis property.
     *
     * @param value allowed object is
     *              {@link AnalysisType }
     */
    public void setAnalysis(AnalysisType value) {
        this.analysis = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

}
