//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ProcessDefinitionsType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ProcessDefinitionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Process" type="{http://www.ict.swin.edu.au/serendip/types}ProcessDefinitionType" maxOccurs="unbounded"/>
 *         &lt;element name="InterProcessRegulationUnitRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="QoS" type="{http://www.ict.swin.edu.au/serendip/types}QoSType" minOccurs="0"/>
 *         &lt;element name="Traffic" type="{http://www.ict.swin.edu.au/serendip/types}TrafficModelType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="descr" type="{http://www.w3.org/2001/XMLSchema}string" default="optional" />
 *       &lt;attribute name="routingPolicy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="flowControlPolicy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="monitoringPolicy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessDefinitionsType", propOrder = {
        "process",
        "interProcessRegulationUnitRef",
        "qoS",
        "traffic"
})
public class ProcessDefinitionsType {

    @XmlElement(name = "Process", required = true)
    protected List<ProcessDefinitionType> process;
    @XmlElement(name = "InterProcessRegulationUnitRef")
    protected List<String> interProcessRegulationUnitRef;
    @XmlElement(name = "QoS")
    protected QoSType qoS;
    @XmlElement(name = "Traffic")
    protected TrafficModelType traffic;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "descr")
    protected String descr;
    @XmlAttribute(name = "routingPolicy")
    protected String routingPolicy;
    @XmlAttribute(name = "flowControlPolicy")
    protected String flowControlPolicy;
    @XmlAttribute(name = "monitoringPolicy")
    protected String monitoringPolicy;
    @XmlAttribute(name = "state")
    protected String state;

    /**
     * Gets the value of the process property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the process property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcess().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessDefinitionType }
     */
    public List<ProcessDefinitionType> getProcess() {
        if (process == null) {
            process = new ArrayList<ProcessDefinitionType>();
        }
        return this.process;
    }

    /**
     * Gets the value of the interProcessRegulationUnitRef property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interProcessRegulationUnitRef property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterProcessRegulationUnitRef().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getInterProcessRegulationUnitRef() {
        if (interProcessRegulationUnitRef == null) {
            interProcessRegulationUnitRef = new ArrayList<String>();
        }
        return this.interProcessRegulationUnitRef;
    }

    /**
     * Gets the value of the qoS property.
     *
     * @return possible object is
     * {@link QoSType }
     */
    public QoSType getQoS() {
        return qoS;
    }

    /**
     * Sets the value of the qoS property.
     *
     * @param value allowed object is
     *              {@link QoSType }
     */
    public void setQoS(QoSType value) {
        this.qoS = value;
    }

    /**
     * Gets the value of the traffic property.
     *
     * @return possible object is
     * {@link TrafficModelType }
     */
    public TrafficModelType getTraffic() {
        return traffic;
    }

    /**
     * Sets the value of the traffic property.
     *
     * @param value allowed object is
     *              {@link TrafficModelType }
     */
    public void setTraffic(TrafficModelType value) {
        this.traffic = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the descr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescr() {
        if (descr == null) {
            return "optional";
        } else {
            return descr;
        }
    }

    /**
     * Sets the value of the descr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescr(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the routingPolicy property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoutingPolicy() {
        return routingPolicy;
    }

    /**
     * Sets the value of the routingPolicy property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoutingPolicy(String value) {
        this.routingPolicy = value;
    }

    /**
     * Gets the value of the flowControlPolicy property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFlowControlPolicy() {
        return flowControlPolicy;
    }

    /**
     * Sets the value of the flowControlPolicy property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFlowControlPolicy(String value) {
        this.flowControlPolicy = value;
    }

    /**
     * Gets the value of the monitoringPolicy property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMonitoringPolicy() {
        return monitoringPolicy;
    }

    /**
     * Sets the value of the monitoringPolicy property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMonitoringPolicy(String value) {
        this.monitoringPolicy = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setState(String value) {
        this.state = value;
    }

}
