//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QoSType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="QoSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Throughput" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Capacity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Utility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QoSType", propOrder = {
        "responseTime",
        "throughput",
        "capacity",
        "utility",
        "price"
})
public class QoSType {

    @XmlElement(name = "ResponseTime")
    protected String responseTime;
    @XmlElement(name = "Throughput")
    protected String throughput;
    @XmlElement(name = "Capacity")
    protected String capacity;
    @XmlElement(name = "Utility")
    protected String utility;
    @XmlElement(name = "Price")
    protected String price;

    /**
     * Gets the value of the responseTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * Sets the value of the responseTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResponseTime(String value) {
        this.responseTime = value;
    }

    /**
     * Gets the value of the throughput property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getThroughput() {
        return throughput;
    }

    /**
     * Sets the value of the throughput property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setThroughput(String value) {
        this.throughput = value;
    }

    /**
     * Gets the value of the capacity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCapacity(String value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the utility property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUtility() {
        return utility;
    }

    /**
     * Sets the value of the utility property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUtility(String value) {
        this.utility = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrice(String value) {
        this.price = value;
    }

}
