//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for RoleLinkedFactType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="RoleLinkedFactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcquisitionRegime">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="mode" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Active"/>
 *                       &lt;enumeration value="Passive"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="SyncInterval" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProvisionRegime">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="mode" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Active"/>
 *                       &lt;enumeration value="Passive"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="SyncInterval" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OnChange" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="monitor" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="provide" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleLinkedFactType", namespace = "http://www.swin.edu.au/ict/road/role", propOrder = {
        "acquisitionRegime",
        "provisionRegime",
        "onChange"
})
public class RoleLinkedFactType {

    @XmlElement(name = "AcquisitionRegime", namespace = "", required = true)
    protected RoleLinkedFactType.AcquisitionRegime acquisitionRegime;
    @XmlElement(name = "ProvisionRegime", namespace = "", required = true)
    protected RoleLinkedFactType.ProvisionRegime provisionRegime;
    @XmlElement(name = "OnChange", namespace = "")
    protected boolean onChange;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "monitor", required = true)
    protected boolean monitor;
    @XmlAttribute(name = "provide", required = true)
    protected boolean provide;

    /**
     * Gets the value of the acquisitionRegime property.
     *
     * @return possible object is
     * {@link RoleLinkedFactType.AcquisitionRegime }
     */
    public RoleLinkedFactType.AcquisitionRegime getAcquisitionRegime() {
        return acquisitionRegime;
    }

    /**
     * Sets the value of the acquisitionRegime property.
     *
     * @param value allowed object is
     *              {@link RoleLinkedFactType.AcquisitionRegime }
     */
    public void setAcquisitionRegime(RoleLinkedFactType.AcquisitionRegime value) {
        this.acquisitionRegime = value;
    }

    /**
     * Gets the value of the provisionRegime property.
     *
     * @return possible object is
     * {@link RoleLinkedFactType.ProvisionRegime }
     */
    public RoleLinkedFactType.ProvisionRegime getProvisionRegime() {
        return provisionRegime;
    }

    /**
     * Sets the value of the provisionRegime property.
     *
     * @param value allowed object is
     *              {@link RoleLinkedFactType.ProvisionRegime }
     */
    public void setProvisionRegime(RoleLinkedFactType.ProvisionRegime value) {
        this.provisionRegime = value;
    }

    /**
     * Gets the value of the onChange property.
     */
    public boolean isOnChange() {
        return onChange;
    }

    /**
     * Sets the value of the onChange property.
     */
    public void setOnChange(boolean value) {
        this.onChange = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the monitor property.
     */
    public boolean isMonitor() {
        return monitor;
    }

    /**
     * Sets the value of the monitor property.
     */
    public void setMonitor(boolean value) {
        this.monitor = value;
    }

    /**
     * Gets the value of the provide property.
     */
    public boolean isProvide() {
        return provide;
    }

    /**
     * Sets the value of the provide property.
     */
    public void setProvide(boolean value) {
        this.provide = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Active"/>
     *             &lt;enumeration value="Passive"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="SyncInterval" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AcquisitionRegime {

        @XmlAttribute(name = "mode", required = true)
        protected String mode;
        @XmlAttribute(name = "SyncInterval", required = true)
        protected int syncInterval;

        /**
         * Gets the value of the mode property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the syncInterval property.
         */
        public int getSyncInterval() {
            return syncInterval;
        }

        /**
         * Sets the value of the syncInterval property.
         */
        public void setSyncInterval(int value) {
            this.syncInterval = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="mode" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Active"/>
     *             &lt;enumeration value="Passive"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="SyncInterval" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProvisionRegime {

        @XmlAttribute(name = "mode", required = true)
        protected String mode;
        @XmlAttribute(name = "SyncInterval", required = true)
        protected int syncInterval;

        /**
         * Gets the value of the mode property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the syncInterval property.
         */
        public int getSyncInterval() {
            return syncInterval;
        }

        /**
         * Sets the value of the syncInterval property.
         */
        public void setSyncInterval(int value) {
            this.syncInterval = value;
        }

    }

}
