//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for RoleType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="RoleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LinkedFacts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/role}RoleLinkedFactType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ManagementResponsibilities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tasks" type="{http://www.ict.swin.edu.au/serendip/types}TasksType" minOccurs="0"/>
 *         &lt;element name="Monitor" type="{http://www.swin.edu.au/ict/road/monitor}MonitorType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="monitoringPolicy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entryRole" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="synchronization" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="routing" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleType", namespace = "http://www.swin.edu.au/ict/road/role", propOrder = {
        "description",
        "linkedFacts",
        "managementResponsibilities",
        "tasks",
        "monitor"
})
public class RoleType {

    @XmlElement(name = "Description", namespace = "")
    protected String description;
    @XmlElement(name = "LinkedFacts", namespace = "")
    protected RoleType.LinkedFacts linkedFacts;
    @XmlElement(name = "ManagementResponsibilities", namespace = "")
    protected String managementResponsibilities;
    @XmlElement(name = "Tasks", namespace = "")
    protected TasksType tasks;
    @XmlElement(name = "Monitor", namespace = "")
    protected MonitorType monitor;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "monitoringPolicy")
    protected String monitoringPolicy;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "entryRole")
    protected Boolean entryRole;
    @XmlAttribute(name = "synchronization")
    protected String synchronization;
    @XmlAttribute(name = "routing")
    protected String routing;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the linkedFacts property.
     *
     * @return possible object is
     * {@link RoleType.LinkedFacts }
     */
    public RoleType.LinkedFacts getLinkedFacts() {
        return linkedFacts;
    }

    /**
     * Sets the value of the linkedFacts property.
     *
     * @param value allowed object is
     *              {@link RoleType.LinkedFacts }
     */
    public void setLinkedFacts(RoleType.LinkedFacts value) {
        this.linkedFacts = value;
    }

    /**
     * Gets the value of the managementResponsibilities property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getManagementResponsibilities() {
        return managementResponsibilities;
    }

    /**
     * Sets the value of the managementResponsibilities property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setManagementResponsibilities(String value) {
        this.managementResponsibilities = value;
    }

    /**
     * Gets the value of the tasks property.
     *
     * @return possible object is
     * {@link TasksType }
     */
    public TasksType getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     *
     * @param value allowed object is
     *              {@link TasksType }
     */
    public void setTasks(TasksType value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the monitor property.
     *
     * @return possible object is
     * {@link MonitorType }
     */
    public MonitorType getMonitor() {
        return monitor;
    }

    /**
     * Sets the value of the monitor property.
     *
     * @param value allowed object is
     *              {@link MonitorType }
     */
    public void setMonitor(MonitorType value) {
        this.monitor = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the monitoringPolicy property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMonitoringPolicy() {
        return monitoringPolicy;
    }

    /**
     * Sets the value of the monitoringPolicy property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMonitoringPolicy(String value) {
        this.monitoringPolicy = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the entryRole property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isEntryRole() {
        if (entryRole == null) {
            return false;
        } else {
            return entryRole;
        }
    }

    /**
     * Sets the value of the entryRole property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setEntryRole(Boolean value) {
        this.entryRole = value;
    }

    /**
     * Gets the value of the synchronization property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSynchronization() {
        return synchronization;
    }

    /**
     * Sets the value of the synchronization property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSynchronization(String value) {
        this.synchronization = value;
    }

    /**
     * Gets the value of the routing property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRouting() {
        return routing;
    }

    /**
     * Sets the value of the routing property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRouting(String value) {
        this.routing = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/role}RoleLinkedFactType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "fact"
    })
    public static class LinkedFacts {

        @XmlElement(name = "Fact", namespace = "", required = true)
        protected List<RoleLinkedFactType> fact;

        /**
         * Gets the value of the fact property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fact property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFact().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link RoleLinkedFactType }
         */
        public List<RoleLinkedFactType> getFact() {
            if (fact == null) {
                fact = new ArrayList<RoleLinkedFactType>();
            }
            return this.fact;
        }

    }

}
