//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VirtualServiceNetwork" type="{http://www.ict.swin.edu.au/serendip/types}ProcessDefinitionsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InterVSNRegulation" type="{http://www.ict.swin.edu.au/serendip/types}InterVSNRegulationType" minOccurs="0"/>
 *         &lt;element name="InterProcessRegulationUnits" type="{http://www.ict.swin.edu.au/serendip/types}InterProcessRegulationUnitsType" minOccurs="0"/>
 *         &lt;element name="InterCollaborationRegulationUnits" type="{http://www.ict.swin.edu.au/serendip/types}InterCollaborationRegulationUnitsType" minOccurs="0"/>
 *         &lt;element name="CollaborationUnits" type="{http://www.ict.swin.edu.au/serendip/types}CollaborationUnitsType" minOccurs="0"/>
 *         &lt;element name="Messages" type="{http://www.ict.swin.edu.au/serendip/types}MessagesType" minOccurs="0"/>
 *         &lt;element name="Events" type="{http://www.ict.swin.edu.au/serendip/types}EventsType" minOccurs="0"/>
 *         &lt;element name="Facts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/fact}FactType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Roles" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Role" type="{http://www.swin.edu.au/ict/road/role}RoleType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Contracts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Contract" type="{http://www.swin.edu.au/ict/road/contract}ContractType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ServiceBindings" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServiceBinding" type="{http://www.swin.edu.au/ict/road/player}PlayerBindingType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OrganiserBinding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OperationalManagerBinding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MessageAnalyzers" type="{http://www.ict.swin.edu.au/serendip/types}MessageAnalyzersType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataDir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="routingRuleFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="compositeRuleFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="globalRegulation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "virtualServiceNetwork",
        "interVSNRegulation",
        "interProcessRegulationUnits",
        "interCollaborationRegulationUnits",
        "collaborationUnits",
        "messages",
        "events",
        "facts",
        "roles",
        "contracts",
        "serviceBindings",
        "organiserBinding",
        "operationalManagerBinding",
        "description",
        "messageAnalyzers"
})
@XmlRootElement(name = "ServiceNetwork", namespace = "http://www.swin.edu.au/ict/road/smc")
public class ServiceNetwork {

    @XmlElement(name = "VirtualServiceNetwork", namespace = "")
    protected List<ProcessDefinitionsType> virtualServiceNetwork;
    @XmlElement(name = "InterVSNRegulation", namespace = "")
    protected InterVSNRegulationType interVSNRegulation;
    @XmlElement(name = "InterProcessRegulationUnits", namespace = "")
    protected InterProcessRegulationUnitsType interProcessRegulationUnits;
    @XmlElement(name = "InterCollaborationRegulationUnits", namespace = "")
    protected InterCollaborationRegulationUnitsType interCollaborationRegulationUnits;
    @XmlElement(name = "CollaborationUnits", namespace = "")
    protected CollaborationUnitsType collaborationUnits;
    @XmlElement(name = "Messages", namespace = "")
    protected MessagesType messages;
    @XmlElement(name = "Events", namespace = "")
    protected EventsType events;
    @XmlElement(name = "Facts", namespace = "")
    protected ServiceNetwork.Facts facts;
    @XmlElement(name = "Roles", namespace = "")
    protected ServiceNetwork.Roles roles;
    @XmlElement(name = "Contracts", namespace = "")
    protected ServiceNetwork.Contracts contracts;
    @XmlElement(name = "ServiceBindings", namespace = "")
    protected ServiceNetwork.ServiceBindings serviceBindings;
    @XmlElement(name = "OrganiserBinding", namespace = "")
    protected String organiserBinding;
    @XmlElement(name = "OperationalManagerBinding", namespace = "")
    protected String operationalManagerBinding;
    @XmlElement(name = "Description", namespace = "")
    protected String description;
    @XmlElement(name = "MessageAnalyzers", namespace = "")
    protected MessageAnalyzersType messageAnalyzers;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "dataDir", required = true)
    protected String dataDir;
    @XmlAttribute(name = "routingRuleFile")
    protected String routingRuleFile;
    @XmlAttribute(name = "compositeRuleFile")
    protected String compositeRuleFile;
    @XmlAttribute(name = "globalRegulation")
    protected String globalRegulation;

    /**
     * Gets the value of the virtualServiceNetwork property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the virtualServiceNetwork property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVirtualServiceNetwork().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessDefinitionsType }
     */
    public List<ProcessDefinitionsType> getVirtualServiceNetwork() {
        if (virtualServiceNetwork == null) {
            virtualServiceNetwork = new ArrayList<ProcessDefinitionsType>();
        }
        return this.virtualServiceNetwork;
    }

    /**
     * Gets the value of the interVSNRegulation property.
     *
     * @return possible object is
     * {@link InterVSNRegulationType }
     */
    public InterVSNRegulationType getInterVSNRegulation() {
        return interVSNRegulation;
    }

    /**
     * Sets the value of the interVSNRegulation property.
     *
     * @param value allowed object is
     *              {@link InterVSNRegulationType }
     */
    public void setInterVSNRegulation(InterVSNRegulationType value) {
        this.interVSNRegulation = value;
    }

    /**
     * Gets the value of the interProcessRegulationUnits property.
     *
     * @return possible object is
     * {@link InterProcessRegulationUnitsType }
     */
    public InterProcessRegulationUnitsType getInterProcessRegulationUnits() {
        return interProcessRegulationUnits;
    }

    /**
     * Sets the value of the interProcessRegulationUnits property.
     *
     * @param value allowed object is
     *              {@link InterProcessRegulationUnitsType }
     */
    public void setInterProcessRegulationUnits(InterProcessRegulationUnitsType value) {
        this.interProcessRegulationUnits = value;
    }

    /**
     * Gets the value of the interCollaborationRegulationUnits property.
     *
     * @return possible object is
     * {@link InterCollaborationRegulationUnitsType }
     */
    public InterCollaborationRegulationUnitsType getInterCollaborationRegulationUnits() {
        return interCollaborationRegulationUnits;
    }

    /**
     * Sets the value of the interCollaborationRegulationUnits property.
     *
     * @param value allowed object is
     *              {@link InterCollaborationRegulationUnitsType }
     */
    public void setInterCollaborationRegulationUnits(InterCollaborationRegulationUnitsType value) {
        this.interCollaborationRegulationUnits = value;
    }

    /**
     * Gets the value of the collaborationUnits property.
     *
     * @return possible object is
     * {@link CollaborationUnitsType }
     */
    public CollaborationUnitsType getCollaborationUnits() {
        return collaborationUnits;
    }

    /**
     * Sets the value of the collaborationUnits property.
     *
     * @param value allowed object is
     *              {@link CollaborationUnitsType }
     */
    public void setCollaborationUnits(CollaborationUnitsType value) {
        this.collaborationUnits = value;
    }

    /**
     * Gets the value of the messages property.
     *
     * @return possible object is
     * {@link MessagesType }
     */
    public MessagesType getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     *
     * @param value allowed object is
     *              {@link MessagesType }
     */
    public void setMessages(MessagesType value) {
        this.messages = value;
    }

    /**
     * Gets the value of the events property.
     *
     * @return possible object is
     * {@link EventsType }
     */
    public EventsType getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     *
     * @param value allowed object is
     *              {@link EventsType }
     */
    public void setEvents(EventsType value) {
        this.events = value;
    }

    /**
     * Gets the value of the facts property.
     *
     * @return possible object is
     * {@link ServiceNetwork.Facts }
     */
    public ServiceNetwork.Facts getFacts() {
        return facts;
    }

    /**
     * Sets the value of the facts property.
     *
     * @param value allowed object is
     *              {@link ServiceNetwork.Facts }
     */
    public void setFacts(ServiceNetwork.Facts value) {
        this.facts = value;
    }

    /**
     * Gets the value of the roles property.
     *
     * @return possible object is
     * {@link ServiceNetwork.Roles }
     */
    public ServiceNetwork.Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     *
     * @param value allowed object is
     *              {@link ServiceNetwork.Roles }
     */
    public void setRoles(ServiceNetwork.Roles value) {
        this.roles = value;
    }

    /**
     * Gets the value of the contracts property.
     *
     * @return possible object is
     * {@link ServiceNetwork.Contracts }
     */
    public ServiceNetwork.Contracts getContracts() {
        return contracts;
    }

    /**
     * Sets the value of the contracts property.
     *
     * @param value allowed object is
     *              {@link ServiceNetwork.Contracts }
     */
    public void setContracts(ServiceNetwork.Contracts value) {
        this.contracts = value;
    }

    /**
     * Gets the value of the serviceBindings property.
     *
     * @return possible object is
     * {@link ServiceNetwork.ServiceBindings }
     */
    public ServiceNetwork.ServiceBindings getServiceBindings() {
        return serviceBindings;
    }

    /**
     * Sets the value of the serviceBindings property.
     *
     * @param value allowed object is
     *              {@link ServiceNetwork.ServiceBindings }
     */
    public void setServiceBindings(ServiceNetwork.ServiceBindings value) {
        this.serviceBindings = value;
    }

    /**
     * Gets the value of the organiserBinding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrganiserBinding() {
        return organiserBinding;
    }

    /**
     * Sets the value of the organiserBinding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrganiserBinding(String value) {
        this.organiserBinding = value;
    }

    /**
     * Gets the value of the operationalManagerBinding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOperationalManagerBinding() {
        return operationalManagerBinding;
    }

    /**
     * Sets the value of the operationalManagerBinding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOperationalManagerBinding(String value) {
        this.operationalManagerBinding = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the messageAnalyzers property.
     *
     * @return possible object is
     * {@link MessageAnalyzersType }
     */
    public MessageAnalyzersType getMessageAnalyzers() {
        return messageAnalyzers;
    }

    /**
     * Sets the value of the messageAnalyzers property.
     *
     * @param value allowed object is
     *              {@link MessageAnalyzersType }
     */
    public void setMessageAnalyzers(MessageAnalyzersType value) {
        this.messageAnalyzers = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dataDir property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDataDir() {
        return dataDir;
    }

    /**
     * Sets the value of the dataDir property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDataDir(String value) {
        this.dataDir = value;
    }

    /**
     * Gets the value of the routingRuleFile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoutingRuleFile() {
        return routingRuleFile;
    }

    /**
     * Sets the value of the routingRuleFile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoutingRuleFile(String value) {
        this.routingRuleFile = value;
    }

    /**
     * Gets the value of the compositeRuleFile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCompositeRuleFile() {
        return compositeRuleFile;
    }

    /**
     * Sets the value of the compositeRuleFile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCompositeRuleFile(String value) {
        this.compositeRuleFile = value;
    }

    /**
     * Gets the value of the globalRegulation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGlobalRegulation() {
        return globalRegulation;
    }

    /**
     * Sets the value of the globalRegulation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGlobalRegulation(String value) {
        this.globalRegulation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Contract" type="{http://www.swin.edu.au/ict/road/contract}ContractType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "contract"
    })
    public static class Contracts {

        @XmlElement(name = "Contract", namespace = "")
        protected List<ContractType> contract;

        /**
         * Gets the value of the contract property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contract property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContract().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link ContractType }
         */
        public List<ContractType> getContract() {
            if (contract == null) {
                contract = new ArrayList<ContractType>();
            }
            return this.contract;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/fact}FactType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "fact"
    })
    public static class Facts {

        @XmlElement(name = "Fact", namespace = "", required = true)
        protected List<FactType> fact;

        /**
         * Gets the value of the fact property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fact property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFact().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link FactType }
         */
        public List<FactType> getFact() {
            if (fact == null) {
                fact = new ArrayList<FactType>();
            }
            return this.fact;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Role" type="{http://www.swin.edu.au/ict/road/role}RoleType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "role"
    })
    public static class Roles {

        @XmlElement(name = "Role", namespace = "")
        protected List<RoleType> role;

        /**
         * Gets the value of the role property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the role property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRole().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link RoleType }
         */
        public List<RoleType> getRole() {
            if (role == null) {
                role = new ArrayList<RoleType>();
            }
            return this.role;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ServiceBinding" type="{http://www.swin.edu.au/ict/road/player}PlayerBindingType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "serviceBinding"
    })
    public static class ServiceBindings {

        @XmlElement(name = "ServiceBinding", namespace = "")
        protected List<PlayerBindingType> serviceBinding;

        /**
         * Gets the value of the serviceBinding property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the serviceBinding property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServiceBinding().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link PlayerBindingType }
         */
        public List<PlayerBindingType> getServiceBinding() {
            if (serviceBinding == null) {
                serviceBinding = new ArrayList<PlayerBindingType>();
            }
            return this.serviceBinding;
        }

    }

}
