//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for TermType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="TermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.swin.edu.au/ict/road/term}OperationType"/>
 *         &lt;element name="Direction" type="{http://www.swin.edu.au/ict/road/term}DirectionType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="messageType" default="push">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="push"/>
 *             &lt;enumeration value="pull"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="deonticType" default="permission">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="permission"/>
 *             &lt;enumeration value="obligation"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TermType", namespace = "http://www.swin.edu.au/ict/road/term", propOrder = {
        "operation",
        "direction",
        "description"
})
public class TermType {

    @XmlElement(name = "Operation", namespace = "", required = true)
    protected OperationType operation;
    @XmlElement(name = "Direction", namespace = "", required = true)
    protected DirectionType direction;
    @XmlElement(name = "Description", namespace = "")
    protected String description;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "messageType")
    protected String messageType;
    @XmlAttribute(name = "deonticType")
    protected String deonticType;

    /**
     * Gets the value of the operation property.
     *
     * @return possible object is
     * {@link OperationType }
     */
    public OperationType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     *
     * @param value allowed object is
     *              {@link OperationType }
     */
    public void setOperation(OperationType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the direction property.
     *
     * @return possible object is
     * {@link DirectionType }
     */
    public DirectionType getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     *
     * @param value allowed object is
     *              {@link DirectionType }
     */
    public void setDirection(DirectionType value) {
        this.direction = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the messageType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessageType() {
        if (messageType == null) {
            return "push";
        } else {
            return messageType;
        }
    }

    /**
     * Sets the value of the messageType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the deonticType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeonticType() {
        if (deonticType == null) {
            return "permission";
        } else {
            return deonticType;
        }
    }

    /**
     * Sets the value of the deonticType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeonticType(String value) {
        this.deonticType = value;
    }

}
