//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 06:11:50 PM AEDT 
//


package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrafficModelType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="TrafficModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinCapacity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxCapacity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Interval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Preference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficModelType", propOrder = {
        "minCapacity",
        "maxCapacity",
        "interval",
        "preference"
})
public class TrafficModelType {

    @XmlElement(name = "MinCapacity")
    protected String minCapacity;
    @XmlElement(name = "MaxCapacity")
    protected String maxCapacity;
    @XmlElement(name = "Interval")
    protected String interval;
    @XmlElement(name = "Preference")
    protected String preference;

    /**
     * Gets the value of the minCapacity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMinCapacity() {
        return minCapacity;
    }

    /**
     * Sets the value of the minCapacity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMinCapacity(String value) {
        this.minCapacity = value;
    }

    /**
     * Gets the value of the maxCapacity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * Sets the value of the maxCapacity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxCapacity(String value) {
        this.maxCapacity = value;
    }

    /**
     * Gets the value of the interval property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInterval(String value) {
        this.interval = value;
    }

    /**
     * Gets the value of the preference property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPreference() {
        return preference;
    }

    /**
     * Sets the value of the preference property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPreference(String value) {
        this.preference = value;
    }

}
