global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "analyzeResponseV1"
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
   actions.Forward("SC-VC.rentVehicle.Req","RentVehicleReq.xsl",$msg);
end

rule "analyzeResponseV2"
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
   actions.Forward("SC-TC2.orderTow.Req","OrderTC2TowReq.xsl",$msg);
end

rule "analyzeResponseV4"
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
   actions.Forward("SC-GC2.orderRepair.Req","OrderRepairReqGC2.xsl",$msg);
end

rule "analyzeResponseV5"
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
   actions.Forward("SC-HC.rentRoom.Req","RentRoomReq.xsl",$msg);
end

rule "sendGuideListResponse"
  when
   $msg : RoleServiceMessage(operationName== "sendGuideListResponse", state=="forwardable")
  then
   actions.Forward("SC-TG.bookGuide.Req","BookGuideReq.xsl",$msg);
   actions.Forward("SC-VR.rentVehicle.Req","RentVehicleReq.xsl",$msg);
end