global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "bookTour"
  when
   $e1 : EventRecord(eventId == "eBookTour")
  then
   disabledSet.disable("bookTour");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TC.bookTour.Req","CM-TC.sendTourRequirements.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"BookTour.xsl","BookTour");
   actions.ExecuteTask(exMsg);
end