global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.common.VSNInstance;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "orderRepair"
  when
   $e1 : EventRecord(eventId == "eRepairReqdFromGC3BySC")
  then
   disabledSet.disable("orderRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-GC3.orderRepair.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRepairGC3.xsl","OrderRepair");
   actions.ExecuteTask(exMsg);
end

rule "doRepair"
  when
   $e1 : EventRecord(eventId == "eReceivedParts")
  then
   disabledSet.disable("doRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-TC2.sendGCLocation.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"DoRepairGC3.xsl","DoRepair");
   actions.ExecuteTask(exMsg);
end