global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "orderRepairResponse"
  when
   $msg : RoleServiceMessage(operationName== "orderRepairResponse", state=="forwardable")
  then
   actions.Forward("GC3-TC2.sendGCLocation.Req","SendGC3TC2LocationReq.xsl",$msg);
end

rule "doRepairResponse"
  when
   $msg : RoleServiceMessage(operationName== "doRepairResponse", state=="forwardable")
  then
   actions.Forward("SC-GC3.payRepair.Req","PayGC3Req.xsl",$msg);
end