global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "notifyTaxiBookingTX2"
  when
   $e1 : EventRecord(eventId == "eNotifyTaxiBookingReqdFromTX2")
  then
   disabledSet.disable("notifyTaxiBookingTX2");
   MessageWrapper [] msgs = actions.Pull(new String []{"TX2-MM.notifyTaxiBooking.Req"});
   actions.ExecuteTask(msgs[0]);
end