global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "notifyTaxiBooking"
  when
   $e1 : EventRecord(eventId == "eNotifyTaxiBookingReqd")
  then
   disabledSet.disable("notifyTaxiBooking");
   MessageWrapper [] msgs = actions.Pull(new String []{"TX-MM.notifyTaxiBooking.Req"});
   actions.ExecuteTask(msgs[0]);
end