global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "orderTaxi"
    when
		$msg : MessageReceivedEvent(operationName == "orderTaxi",  response ==false)
    then
		actions.publishEvent("eOrderTaxiReqdTX2",$msg);
end
rule "orderTaxiResponse"
    when
		$msg : MessageReceivedEvent(operationName == "orderTaxi",  response ==true)
    then
		actions.publishEvent("eOrderedTaxiTX2",$msg);
end

rule "sendTaxiInvoice"
    when
		$msg : MessageReceivedEvent(operationName == "sendTaxiInvoice",  response ==false)
    then
		actions.publishEvent("ePayTX2Reqd",$msg);
end

rule "sendTaxiInvoiceResponse"
    when
		$msg : MessageReceivedEvent(operationName == "sendTaxiInvoice",  response ==true)
    then
		actions.publishEvent("eTX2Paid",$msg);
end