global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "analyzeResponseV6"
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
   actions.Forward("SC-GC3.orderRepair.Req","OrderRepairReqGC3.xsl",$msg);
end

rule "payGCResponseV6"
  when
   $msg : RoleServiceMessage(operationName== "payGCResponse", state=="forwardable")
  then
   actions.Forward("SC-GC3.payRepair.Res","PayGC3Res.xsl",$msg);
end