global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.common.VSNInstance;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "payGC3"
  when
   $e1 : EventRecord(eventId == "ePayRepairReqdByGC3")
  then
   disabledSet.disable("payGC3");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-GC3.payRepair.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"PayGC3.xsl","PayGC");
   actions.ExecuteTask(exMsg);
end