global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "selectRepair" salience 1
  when
   $msg : RoleServiceMessage(operationName== "analyzeResponse", state=="forwardable")
  then
  //select one repair
   actions.AlterPath("ruTowingByTowTow,ruTomTowAndMacRepair","ruTowingByMarkTow,ruMarkTowAndMacRepair",$msg);
end