global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "tow2"
  when
   EventRecord(eventId == "eTowReqd") and  EventRecord(eventId == "eGC3LocKnown")
  then
   disabledSet.disable("tow2");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TC2.orderTow.Req","GC3-TC2.sendGCLocation.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"TowTC2.xsl","Tow");
   actions.ExecuteTask(exMsg);
end