global au.edu.swin.ict.road.composite.regulation.sglobal.GlobalActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;

rule "terminateV5"
when
   ($e1 : EventRecord(eventId == "eMMNotify")) and ($e2 : EventRecord(eventId == "eTX2Paid"))
then
    disabledSet.disable("terminateV5");
    actions.TerminateVSNInstance($e1.getClassifier());
end