global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;
import au.edu.swin.ict.road.common.RegulationUnitKeyManagementState;

rule "es8_opr_stage1"
  when
    ( $mpsOpr : ManagementPolicyState (id =="es8_opr", state=="incipient") ) and ( $mpsOrg :
    ManagementPolicyState(id =="es8_org", state=="stage1done") )
  then
    disabledSet.disable("es8_opr_stage1");
    System.out.println("Operational management policy es8_opr_stage1 has been started.");

    oprMgt.addSynchronizationRule("HC","HC_SYN.drl");
    oprMgt.addSynchronizationRule("SC","SC_SYN_Diff.drl");
    oprMgt.updateSynchronizationRule("MM","notify","replace" ,"MM_SYN_Diff_Replace.drl");

    oprMgt.addRoutingRule("HC","HC_Routing.drl");
    oprMgt.updateRoutingRule("SC","analyzeResponse,payGCResponse","replace","SC_Routing_Diff_Replace.drl");
    oprMgt.addRoutingRule("SC","SC_Routing_Diff.drl");

    oprMgt.addPassthroughRule("SC-HC","SC-HC.drl");
    oprMgt.updateGlobalRule("terminateV1","replace" ,"roadside_global_diff_replace.drl");

    oprMgt.addRegulationUnit("RentingRoom");
    oprMgt.addSynchronizationRulesToRegulationUnit("RentingRoom","rentRoom:HC,endRoomRent:HC,payHC:SC");
    oprMgt.addRoutingRulesToRegulationUnit("RentingRoom","payHCResponse:SC,rentRoomResponse:HC,endRoomRentResponse:HC");
    oprMgt.addPassthroughRulesToRegulationUnit("RentingRoom","rentRoom:SC-HC,rentRoomResponse:SC-HC,endRoomRent:SC-HC,endRoomRentResponse:SC-HC,payRoomRent:SC-HC,payRoomRentResponse:SC-HC");
    oprMgt.addRegulationUnitsToProcessRegulationPolicy("HappyTours","HappyToursP1","RentingRoom");

    oprMgt.updateRegulationUnit("RentingRoom","state","active");
    oprMgt.updateRegulationUnitOfProcessRegulationPolicy("HappyTours","HappyToursP1","RentingRoom","state","active");

    System.out.println("Operational management policy es8_opr_stage1 has been completed successfully.");
    $mpsOpr.setState("quiescence");
end