global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;
import au.edu.swin.ict.road.common.RegulationUnitKeyManagementState;

rule "es8_opr_remove_stage1"
  when
    $mpsOpr : ManagementPolicyState (id =="es8_opr_remove", state=="incipient")
  then
    disabledSet.disable("es8_opr_remove_stage1");
    System.out.println("Operational management policy es8_opr_remove_stage1 has been started.");
    
    oprMgt.updateRegulationUnitOfProcessRegulationPolicy("HappyTours","HappyToursP1","RentingRoom","state","passive");
    oprMgt.updateRegulationUnit("RentingRoom","state","passive");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","RentingRoom");

    oprMgt.removeSynchronizationRulesFromRegulationUnit("RentingRoom","rentRoom:HC,endRoomRent:HC,payHC:SC");
    oprMgt.removeRoutingRulesFromRegulationUnit("RentingRoom","payHCResponse:SC,rentRoomResponse:HC,endRoomRentResponse:HC");
    oprMgt.removePassthroughRulesFromRegulationUnit("RentingRoom","rentRoom:SC-HC,rentRoomResponse:SC-HC,endRoomRent:SC-HC,endRoomRentResponse:SC-HC,payRoomRent:SC-HC,payRoomRentResponse:SC-HC");
    oprMgt.removeRegulationUnit("RentingRoom");

    oprMgt.removeSynchronizationRule("HC","rentRoom,endRoomRent");
    oprMgt.removeSynchronizationRule("SC","payHC");
    oprMgt.updateSynchronizationRule("MM","notify","replace" ,"MM_SYN.drl");

    oprMgt.removeRoutingRule("HC","rentRoomResponse,endRoomRentResponse");
    oprMgt.updateRoutingRule("SC","analyzeResponse,payGCResponse","replace","SC_Routing_Diff_ReplaceV2.drl");
    oprMgt.removeRoutingRule("SC","payHCResponse");

    oprMgt.removePassthroughRule("SC-HC","rentRoom,rentRoomResponse,endRoomRent,endRoomRentResponse,payRoomRent,payRoomRentResponse");
    oprMgt.updateGlobalRule("terminateV1","replace" ,"roadside_global_diff_replaceV2.drl");

    System.out.println("Operational management policy es8_opr_remove_stage1 has been completed successfully.");
    $mpsOpr.setState("quiescence");
end