global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "ChangesForC4-fun-add"
  when
    $mps : ManagementPolicyState(id =="remove", state=="incipient")
  then
    $mps.setState("active");
    long start1 = System.nanoTime();
    orgMgt.removeBehaviorUnitFromProcess("EuroCars","EuroCarsP1","bTowingByMarkTow");
    orgMgt.removeBehaviorUnitFromProcess("AnyTrucks","AnyTrucksP1","bTowingByMarkTow");
    orgMgt.removeBehaviorUnitFromProcess("AnyTrucks","AnyTrucksP2","bTowingByMarkTow");
    orgMgt.removeBehaviorUnitFromProcess("HappyTours","HappyToursP1","bTowingBySwiftTow");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","ruTowingBySwiftTow,ruSwiftTowAndMacRepair,ruActivateV2");

    //routing rule changes
    oprMgt.removeRoutingRule("SC","analyzeResponseV10");

    // regulation unit changes
    oprMgt.removeRoutingRulesFromRegulationUnit("ruTowingByMarkTow","analyzeResponseV10:SC");

    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("EuroCars","EuroCarsP1","ruTowingByMarkTow,ruMarkTowAndMacRepair,ruActivateV1");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruTowingByMarkTow,ruMarkTowAndMacRepair,ruActivateV1");
    // State Changes
    long stop1 = System.nanoTime();
    System.out.println("Remove : " + (stop1 - start1)/1000000);
end