import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
import au.edu.swin.ict.road.composite.rules.events.contract.ObligationComplianceEvent;
import au.edu.swin.ict.road.composite.rules.events.contract.TermExecutedEvent;
import au.edu.swin.ict.road.composite.contract.Contract;
import au.edu.swin.ict.road.regulator.FactTupleSpace;

/** Global Variables **/
global Contract contract;
global FactTupleSpace fts;

/** Events **/
declare MessageReceivedEvent
    @role(event)
end


/** Permission Rules **/
rule "getGRLocationin"
    when
		$event : MessageReceivedEvent(operationName == "getGRLocation",  response ==false)
    then
    //	System.out.println("GetGRLocation from MM to GRIN :GRINLocationReqdMM");
		$event.setBlocked(false);
		//Logic to inspect the message

		$event.triggerEvent("GRINLocationReqdMM");
end