import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "sendGCLocation"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==false)
    then
		$msg.triggerEvent("GC2LocKnown");
		$msg.triggerEvent("RepairAcceptGC2");
end

rule "sendGCLocationResponse"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==true)
    then
		$msg.triggerEvent("DeliveredVehicleGC2");
end
