global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.composite.regulation.DisabledRuleSet disabledSet;
import au.edu.swin.ict.serendip.event.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "getGCLocation"
  when
   $e1 : EventRecord(eventId == "GC2LocationReqdSC")
  then
   disabledSet.disable("getGCLocation");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-GC2.getGCLocation.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRepairGC2.xsl","GetGCLocation");
   actions.ExecuteTask(exMsg);
end

rule "getGCLocationFromMM"
  when
   $e1 : EventRecord(eventId == "GC2LocationReqdMM")
  then
   disabledSet.disable("getGCLocationFromMM");
   MessageWrapper [] msgs = actions.Pull(new String []{"MM-GC2.getGCLocation.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRepairFromGC2ByMM.xsl","GetGCLocation");
   actions.ExecuteTask(exMsg);
end

rule "assessRepairTC1"
  when
   $e1 : EventRecord(eventId == "DeliveredVehicleGC2")
  then
   disabledSet.disable("assessRepairTC1");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-TC1.sendGCLocation.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"AssessRepairTC1.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end

rule "assessRepairTC2"
  when
   $e1 : EventRecord(eventId == "DeliveredVehicleGC2")
  then
   disabledSet.disable("assessRepairTC2");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-TC2.sendGCLocation.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"AssessRepairTC2.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end

rule "doRepair"
  when
   $e1 : EventRecord(eventId == "ReceivedParts")
  then
   disabledSet.disable("doRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-PS.orderParts.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"DoRepairGC2.xsl","DoRepair");
   actions.ExecuteTask(exMsg);
end