global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.composite.regulation.DisabledRuleSet disabledSet;
import au.edu.swin.ict.serendip.event.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "orderParts"
  when
   $e1 : EventRecord(eventId == "OrderPartsReq")
  then
   disabledSet.disable("orderParts");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-PS.orderParts.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderParts.xsl","OrderParts");
   actions.ExecuteTask(exMsg);
end