global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "ChangesForfirststep_per"
  when
    $mps : ManagementPolicyState(id =="firststep_per",state=="incipient")
  then
    $mps.setState("active");
    long start1 = System.nanoTime();

    oprMgt.addRegulationMechanism("SimpleMarker","testmech.SimpleMarker","D:\\testing\\testmech.jar");
    oprMgt.updateRegulationMechanism("SimpleMarker","state","active");

    orgMgt.setTaskQoS("GC1","DoRepair","Throughput:350/d,ResponseTime:2d;Throughput:350/d,ResponseTime:3d;Throughput:350/d,ResponseTime:4d");

    oprMgt.addSynchronizationRule("GC1","GC1_SYN_Diff_cs4_per_fs.drl");
    oprMgt.addRegulationUnit("ruRepairPerLevelChange_2d");
    oprMgt.updateRegulationUnit("ruRepairPerLevelChange_2d","state","active");
    oprMgt.addSynchronizationRulesToRegulationUnit("ruRepairPerLevelChange_2d","ruRepairPerLevelChange_2d:GC1");

    oprMgt.addRegulationUnit("ruRepairPerLevelChange_3d");
    oprMgt.updateRegulationUnit("ruRepairPerLevelChange_3d","state","active");
    oprMgt.addSynchronizationRulesToRegulationUnit("ruRepairPerLevelChange_3d","doRepairChangePerfLevel_3d:GC1");

    oprMgt.addSynchronizationRule("TC1","TC1_SYN_Diff_cs5_per.drl");

    oprMgt.addPassthroughRule("MM-TC1","MM-TC1_Diff_cs5_per.drl");
    oprMgt.addPassthroughRule("SC-TC1","SC-TC1_Diff_cs5_per.drl");
    oprMgt.addSynchronizationRule("GC1","GC1_SYN_Diff_cs4_per.drl");

    oprMgt.addPassthroughRule("GC1-TC1","GC1-TC1_Diff_cs6_per.drl");
    oprMgt.addPassthroughRule("SC-GC1","SC-GC1_Diff_cs6_per.drl");

    oprMgt.addRegulationUnit("ruRepairMonitoring2d");
    oprMgt.updateRegulationUnit("ruRepairMonitoring2d","state","active");
    oprMgt.addPassthroughRulesToRegulationUnit("ruRepairMonitoring2d","startRepairMonitor2d:GC1-TC1,endRepairMonitor2d:SC-GC1");

    oprMgt.addRegulationUnit("ruRepairMonitoring3d");
    oprMgt.updateRegulationUnit("ruRepairMonitoring3d","state","active");
    oprMgt.addPassthroughRulesToRegulationUnit("ruRepairMonitoring3d","startRepairMonitor3d:GC1-TC1,endRepairMonitor3d:SC-GC1");

    oprMgt.addRegulationUnit("ruRepairMonitoring2d");
    oprMgt.updateRegulationUnit("ruRepairMonitoring2d","state","active");
    oprMgt.addPassthroughRulesToRegulationUnit("ruRepairMonitoring2d","startRepairMonitor2d:GC1-TC1,endRepairMonitor2d:SC-GC1");

    oprMgt.addRegulationUnit("ruTowMonitor3h");
    oprMgt.updateRegulationUnit("ruTowMonitor3h","state","active");
    oprMgt.addPassthroughRulesToRegulationUnit("ruTowMonitor3h","pickUpMonitor3h:MM-TC1,payTowResponseMonitor3h:SC-TC1");

    oprMgt.addRegulationUnit("ruTowMonitor4h");
    oprMgt.updateRegulationUnit("ruTowMonitor4h","state","active");
    oprMgt.addPassthroughRulesToRegulationUnit("ruTowMonitor4h","pickUpMonitor4h:MM-TC1,payTowResponseMonitor4h:SC-TC1");

    oprMgt.addRegulationUnit("ruRepairPerLevelChange_4d");
    oprMgt.updateRegulationUnit("ruRepairPerLevelChange_4d","state","active");
    oprMgt.addSynchronizationRulesToRegulationUnit("ruRepairPerLevelChange_4d","doRepairChangePerfLevel_4d:GC1");

    oprMgt.addRegulationUnit("ruTowPerLevelChange_3h");
    oprMgt.updateRegulationUnit("ruTowPerLevelChange_3h","state","active");
    oprMgt.addSynchronizationRulesToRegulationUnit("ruTowPerLevelChange_3h","pickUpChangePerfLevel_3h:TC1,deliverGC1ChangePerfLevel_3h:TC1");

    oprMgt.addRegulationUnit("ruTowPerLevelChange_4h");
    oprMgt.updateRegulationUnit("ruTowPerLevelChange_4h","state","active");
    oprMgt.addSynchronizationRulesToRegulationUnit("ruTowPerLevelChange_4h","pickUpChangePerfLevel_4h:TC1,deliverGC1ChangePerfLevel_4h:TC1");

    oprMgt.addRegulationUnitsToProcessRegulationPolicy("HappyTours","HappyToursP1","ruRepairMonitoring2d,ruTowMonitor3h,ruRepairPerLevelChange_2d,ruTowPerLevelChange_3h");
    oprMgt.updateRegulationUnitsOfProcessRegulationPolicy("HappyTours","HappyToursP1","ruRepairMonitoring2d,ruTowMonitor3h,ruRepairPerLevelChange_2d,ruTowPerLevelChange_3h","state","active");

    oprMgt.addRegulationUnitsToProcessRegulationPolicy("EuroCars","EuroCarsP1","ruRepairMonitoring3d,ruTowMonitor3h,ruRepairPerLevelChange_3d,ruTowPerLevelChange_3h");
    oprMgt.updateRegulationUnitsOfProcessRegulationPolicy("EuroCars","EuroCarsP1","ruTowMonitor3h,ruRepairPerLevelChange_3d,ruTowPerLevelChange_3h","state","active");

    oprMgt.addRegulationUnitsToProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruRepairMonitoring3d, ruTowMonitor3h,ruRepairPerLevelChange_3d,ruTowPerLevelChange_3h");
    oprMgt.updateRegulationUnitsOfProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruRepairMonitoring3d,ruTowMonitor3h,ruRepairPerLevelChange_3d,ruTowPerLevelChange_3h","state","active");
end