import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
import au.edu.swin.ict.road.composite.rules.events.contract.ObligationComplianceEvent;
import au.edu.swin.ict.road.composite.rules.events.contract.TermExecutedEvent;
import au.edu.swin.ict.road.composite.contract.Contract;

/** Global Variables **/
global Contract contract;

/** Events **/
declare MessageReceivedEvent
    @role(event)
end

declare TermExecutedEvent
    @role(event)
    @expires(24h)
end

declare ObligationComplianceEvent
    @role(event)
    @expires(24h)
end

/** Permission Rules **/
rule "Pay Bill"
    when
		$event : MessageReceivedEvent(operationName == "payBill")
    then
    	System.out.println("Bill order request from Waiter to Cashier");
		$event.setBlocked(false);	
		$event.triggerEvent("","");
end
