import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
import au.edu.swin.ict.road.composite.rules.events.contract.ObligationComplianceEvent;
import au.edu.swin.ict.road.composite.rules.events.contract.TermExecutedEvent;
import au.edu.swin.ict.road.composite.contract.Contract;
import au.edu.swin.ict.road.regulator.FactTupleSpace;

/** Global Variables **/
global Contract contract;
global FactTupleSpace fts;

/** Events **/
declare MessageReceivedEvent
    @role(event)
end

declare TermExecutedEvent
    @role(event)
    @expires(24h)
end

declare ObligationComplianceEvent
    @role(event)
    @expires(24h)
end

/** Permission Rules **/
rule "complain"
    when
		$event : MessageReceivedEvent(operationName == "complain",  response ==false)
    then
    //	System.out.println("Complain from MM to CO : ComplainRcvd");
		$event.setBlocked(false);	
		//Logic to inspect the message
	
		$event.triggerEvent("ComplainRcvd");
		
end
rule "complainResponse"
    when
		$event : MessageReceivedEvent(operationName == "complain",  response ==true)
    then
    //	System.out.println("Complain response from CO to MM : MMNotif");
		$event.setBlocked(false);	
		//Logic to inspect the message
	
		$event.triggerEvent("MMNotif"); 
		//$event.triggerEvent("CaseClosed");
		
end

rule "notifyRoomPayment"
    when
		$event : MessageReceivedEvent(operationName == "notifyRoomPayment",  response ==false)
    then
    	//System.out.println("NotifyRoomPayment from CO to MM : NotifyRoomPaymentReqd");
		$event.setBlocked(false);
		//Logic to inspect the message

		$event.triggerEvent("NotifyRoomPaymentReqd");
		//$event.triggerEvent("CaseClosed");
end

rule "notifyVehiclePayment"
    when
		$event : MessageReceivedEvent(operationName == "notifyVehiclePayment",  response ==false)
    then
    	//System.out.println("NotifyVehiclePayment from CO to MM : NotifyVehiclePaymentReqd");
		$event.setBlocked(false);
		//Logic to inspect the message

		$event.triggerEvent("NotifyVehiclePaymentReqd");
		//$event.triggerEvent("CaseClosed");
end