global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "tow"
  when
   EventRecord(eventId == "eTowReqd") and  EventRecord(eventId == "eGC2LocKnown")
  then
   disabledSet.disable("tow");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TC4.orderTow.Req","GC4-TC4.sendGCLocation.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"TowTC4.xsl","Tow");
   actions.ExecuteTask(exMsg);
end