global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "towResponse"
  when
   $msg : RoleServiceMessage(operationName== "towResponse", state=="forwardable")
  then
   actions.Forward("SC-TC6.payTow.Req","PayTC5Req.xsl",$msg);
   actions.Forward("GC2-TC6.sendGCLocation.Res","SendGC6LocationRes.xsl",$msg);
end