global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;
rule "notify"
  when
   $e1 : EventRecord(eventId == "eEchoX1Res")
  then
   disabledSet.disable("notify");
   MessageWrapper [] msgs = actions.Pull(new String []{"X0-X1.echo.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"Notify.xsl","EchoResponse");
   exMsg.setUserResponse(true);
   actions.ExecuteTask(exMsg);
end