global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.common.VSNInstance;
import au.edu.swin.ict.road.composite.message.MessageWrapper;
rule "payLF"
  when
   $e1 : EventRecord(eventId == "ePayLFReqd")
  then
   disabledSet.disable("payLF");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-LF.payLegalAid.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"PayLF.xsl","PayLF");
   actions.ExecuteTask(exMsg);
end