orgMgt.updateProcessOfVSN("AnyTrucks","AnyTrucksP1","CoT","eMMNotify * HCPaid");
orgMgt.addBehaviorUnitToProcess("AnyTrucks","AnyTrucksP1","bRentingRoom");
oprMgt.addRegulationUnitsToProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruRentingRoom,ruTerminateV1");
orgMgt.removeBehaviorUnitFromProcess("AnyTrucks","AnyTrucksP1","bRentingVehicle");
oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruRentingVehicle,ruTerminateV2");
oprMgt.updateRegulationUnitsOfProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruRentingRoom,ruTerminateV1","state","active");
orgMgt.addBehaviorUnitToProcess("AnyTrucks","AnyTrucksP2","bRepairingByAutoRepair");
oprMgt.addRegulationUnitsToProcessRegulationPolicy("AnyTrucks","AnyTrucksP2","ruRepairingByAutoRepair,ruSwiftTowAndAutoRepair");
orgMgt.removeBehaviorUnitFromProcess("AnyTrucks","AnyTrucksP2","bRepairingByNickRepair");
oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("AnyTrucks","AnyTrucksP2","ruRepairingByNickRepair,ruNickRepairAndTowTow");
oprMgt.updateRegulationUnitsOfProcessRegulationPolicy("AnyTrucks","AnyTrucksP2","ruRepairingByAutoRepair,
ruSwiftTowAndAutoRepair","state","active");