global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;
import au.edu.swin.ict.road.common.RegulationUnitKeyManagementState;

rule "es10_opr_remove_stage1"
  when
    $mpsOpr : ManagementPolicyState (id =="es10_opr_remove", state=="incipient")
  then
    disabledSet.disable("es10_opr_remove_stage1");
    System.out.println("Operational management policy es10_opr_remove_stage1 has been started.");

    oprMgt.updateRegulationUnitOfProcessRegulationPolicy("HappyTours","HappyToursP1","HiringTaxi","state","passive");
    oprMgt.updateRegulationUnit("HiringTaxi","state","passive");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","HiringTaxi");

    oprMgt.removeSynchronizationRulesFromRegulationUnit("HiringTaxi","orderTaxi:TX,notifyTaxiBooking:MM,payTX:SC");
    oprMgt.removeRoutingRulesFromRegulationUnit("HiringTaxi","payTXResponse:SC,orderTaxiResponse:TX");
    oprMgt.removePassthroughRulesFromRegulationUnit("HiringTaxi","orderTaxi:SC-TX, notifyTaxiBooking:TX-MM, sendTaxiInvoice:SC-TX, sendTaxiInvoiceResponse:SC-TX");
    oprMgt.removeRegulationUnit("HiringTaxi");

    oprMgt.removeSynchronizationRule("TX","orderTaxi");
    oprMgt.removeSynchronizationRule("SC","payTX");

    oprMgt.removeRoutingRule("TX","towResponse");
    oprMgt.updateRoutingRule("SC","analyzeResponse","replace","SC_Routing_Diff_ReplaceV2.drl");
    oprMgt.removeRoutingRule("SC","payTXResponse");

    oprMgt.removePassthroughRule("TX-MM","notifyTaxiBooking");
    oprMgt.removePassthroughRule("SC-TX","orderTaxi,sendTaxiInvoice,sendTaxiInvoiceResponse");
    oprMgt.updateGlobalRule("terminateV1","replace" ,"roadside_global_diff_replace_V2.drl");

    System.out.println("Operational management policy es10_opr_remove_stage1 has been completed successfully.");
    $mpsOpr.setState("quiescence");
end