global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "es10_org_stage1"
  when
  $mpsOrg : ManagementPolicyState(id =="es10_org", state=="incipient")
   then
   disabledSet.disable("es10_org_stage1");
   System.out.println("Organizational management policy es10_org_stage1 has been started.");
   orgMgt.addRole("TX","14Cabs");
   orgMgt.addTask("TX","OrderTaxi","SC-TX.orderTaxi.Req","SC-TX.orderTaxi.Res,TX-MM.notifyTaxiBooking.Req");
   orgMgt.setTaskInMessage("TX","OrderTaxi","rentVehicle","String:content","String");
   orgMgt.setTaskOutMessage("TX","OrderTaxi","rentVehicle","String:content","String");
   orgMgt.addTask("TX","ProvideTaxiInvoice",null,"SC-TX.sendTaxiInvoice.Req");
   orgMgt.updateTask("TX","ProvideTaxiInvoice","add","mep","one-way");
   orgMgt.setTaskInMessage("TX","ProvideTaxiInvoice","provideTaxiInvoice","String:content","String");
   orgMgt.setServiceBinding("TX","http://localhost:8082/axis2/services/TaxiHireService");

   orgMgt.addTask("SC","PayTX","SC-TX.sendTaxiInvoice.Req","SC-TX.sendTaxiInvoice.Res");
   orgMgt.setTaskInMessage("SC","PayTX","payTX","String:content","String");
   orgMgt.setTaskOutMessage("SC","PayTX","payTX","String:content","String");

   orgMgt.updateTask("SC","Analyze","add","outputs","SC-TX.orderTax.Req");

   orgMgt.addContract("SC-TX","SC","TX");
   orgMgt.addTerm("SC-TX","orderTaxi","AtoB");
   orgMgt.setTermOperation("SC-TX","orderTaxi","orderTaxi","String:content","String");
   orgMgt.addTerm("SC-TX","sendTaxiInvoice","BtoA");
   orgMgt.setTermOperation("SC-TX","sendTaxiInvoice","sendTaxiInvoice","String:content","String");

   orgMgt.addContract("TX-MM","TX","MM");
   orgMgt.addTerm("TX-MM","notifyTaxiBooking","AtoB");
   orgMgt.setTermOperation("TX-MM","notifyTaxiBooking","notifyTaxiBooking","String:content","String");

   orgMgt.updateTaskOfBehaviorUnit("CaseHandling","SC.Analyze","postEP"," eTowReqd * eGCLocKnown * eTowAuthorized * eRentVehicleReqd * eRentVehicleReqd * eOrderTaxiReqd");

   orgMgt.addBehaviorUnit("HiringTaxi");
   orgMgt.addTaskToBehaviorUnit("HiringTaxi","TX.OrderTaxi","eOrderTaxiReqd ","ePayTXReqd * eNotifyTaxiBookingReqd");
   orgMgt.addTaskToBehaviorUnit("HiringTaxi","MM.NotifyTaxiBooking", "eNotifyTaxiBookingReqd",null);
   orgMgt.addTaskToBehaviorUnit("HiringTaxi","SC.PayTX", "ePayTXReqd","eTXPaid");

   orgMgt.addBehaviorUnitToProcess("HappyTours","HappyToursP1","HiringTaxi");
   System.out.println("Organizational management policy es10_org_stage1 has been completed successfully.");
   $mpsOrg.setState("stage1done");
end

rule "es10_org_stage2"
  when
   ( $mpsOrg : ManagementPolicyState(id =="es10_org", state=="stage1done") ) and  ( $mpsOpr :
                                                                               ManagementPolicyState (id
                                                                               =="es10_opr", state=="quiescence"))
  then
   disabledSet.disable("es10_org_stage2");
   System.out.println("Organizational management policy es10_org_stage2 has been started.");
   orgMgt.updateRole("TX","state","active");
   orgMgt.updateContract("TX-MM","state","active");
   orgMgt.updateContract("SC-TX","state","active");
   orgMgt.updateBehaviorUnit("HiringTaxi","state","active");
   System.out.println("Organizational management policy es10_org_stage2 has been completed successfully.");
   $mpsOrg.setState("quiescence");
 end