global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "ChangesForC10-per-add"
  when
    $mps : ManagementPolicyState(id =="add",state=="incipient")
  then
    $mps.setState("active");
    long start1 = System.nanoTime();
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","ruRepairingByNickRepair,ruNickRepairAndTowTow,ruSelectRepair");
    oprMgt.removeRoutingRule("SC","selectRepair");
    oprMgt.removeRegulationUnit("ruSelectRepair");
    orgMgt.removeBehaviorUnitFromProcess("HappyTours","HappyToursP1","bRepairingByNickRepair");
    long stop1 = System.nanoTime();
    System.out.println("Add : " + (stop1 - start1)/1000000);
    $mps.setState("quiescence");
end