global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "sendGCLocation"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==false)
    then
		actions.publishEvent("eGCLocKnown",$msg);
end
rule "sendGCLocationResponse"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==true)
    then
		actions.publishEvent("eDeliveredVehicleToGCByTC2",$msg);
end