global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "payGCResponse"
  when
   $msg : RoleServiceMessage(operationName== "payGCResponse", state=="forwardable")
  then
   actions.Forward("SC-GC1.payRepair.Res","PayGC1Res.xsl",$msg);
   actions.Forward("SC-MM.assist.Res","ComplainRes.xsl",$msg);
end