global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage
import au.edu.swin.ict.road.common.StateRecord
import au.edu.swin.ict.road.common.Weight;
import au.edu.swin.ict.road.common.VSN;
import au.edu.swin.ict.road.common.ProcessManagementState;

rule "requestAssistV9"
  when
   $msg : RoleServiceMessage(operationName== "requestAssist", state=="forwardable")
  then
  actions.Forward("CM-BR.sendBikeRequirements.Req","SendBikeRequirementsReq.xsl",$msg);
end