global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.common.VSNInstance;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "sendRentInvoice"
  when
   $e1 : EventRecord(eventId == "eSendRentInvoice")
  then
   disabledSet.disable("sendRentInvoice");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-BR.sendRentInvoice.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"SendRentInvoice.xsl","SendRentInvoice");
   actions.ExecuteTask(exMsg);
end