global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "notify"
  when
   EventRecord(eventId == "eMMNotify")
  then
   disabledSet.disable("notify");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-MM.assist.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"Notify.xsl","Notify");
   exMsg.setUserResponse(true);
   actions.ExecuteTask(exMsg);
end

rule "notifyTaxiBooking"
  when
   $e1 : EventRecord(eventId == "eNotifyTaxiBookingReqd")
  then
   disabledSet.disable("notifyTaxiBooking");
   MessageWrapper [] msgs = actions.Pull(new String []{"TX-MM.notifyTaxiBooking.Req"});
   actions.ExecuteTask(msgs[0]);
end