global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "tow"
  when
   EventRecord(eventId == "eTowReqdFromTC3") and  EventRecord(eventId == "eSentGC1LocToTC3") and EventRecord(eventId == "eAuthorizedTow")
  then
   disabledSet.disable("tow");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TC3.orderTow.Req","GC1-TC3.sendGCLocation.Req","LF-TC3.authorizeTow.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"TowTC3.xsl","Tow");
   actions.ExecuteTask(exMsg);
end