global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;
rule "notify"
  when
   $e1 : EventRecord(eventId == "eNotify")
  then
   disabledSet.disable("notify");
   MessageWrapper [] msgs = actions.Pull(new String []{"X2-X0.notify.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"Notify.xsl","Notify");
   exMsg.setUserResponse(true);
   actions.ExecuteTask(exMsg);
end