oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruTowPerLevelChange_3h,ruTowMonitor3h");
oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("EuroCars","EuroCarsP1","ruTowPerLevelChange_3h,ruTowMonitor3h");
oprMgt.addRegulationUnitsToProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruTowPerLevelChange_4h,ruTowMonitor4h");
oprMgt.addRegulationUnitsToProcessRegulationPolicy("EuroCars","EuroCarsP1","ruTowPerLevelChange_4h,ruTowMonitor4h");