global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "addTaxiHire_orgMgt_1"
  when
    $mps : ManagementPolicyState (id =="addhire_org", state=="incipient")
  then
    $mps.setState("active");
    orgMgt.updateProcessOfVSN("EuroCars","EuroCarsP1","state", "passive");
    // role-level changes
    // Role TX
    orgMgt.addRole("TX","14Cabs");
    orgMgt.setServiceBinding("TX", "http://localhost:8082/axis2/services/TaxiHireService");
    orgMgt.addTask("TX","OrderTaxi","SC-TX.orderTaxi.Req","SC-TX.orderTaxi.Res,TX-MM.notifyTaxiBooking.Req");
    orgMgt.addTask("TX","ProvideTaxiInvoice", null,"SC-TX.orderTaxi.Res,TX-MM.sendTaxiInvoice.Req");
    orgMgt.updateTask("TX","ProvideTaxiInvoice","set","mep","one-way");
    orgMgt.setTaskQoS("TX","OrderTaxi","Throughput:400/d");
    orgMgt.setTaskOutMessage("TX","OrderTaxi","orderTaxi","String:content","String");
    orgMgt.setTaskInMessage("TX","OrderTaxi","orderTaxi","String:content","String");
    orgMgt.setTaskInMessage("TX","ProvideTaxiInvoice","provideTaxiInvoice","String:content","String");
    // Role MM
    orgMgt.addTask("MM","NotifyTaxiBooking","TX-MM.notifyTaxiBooking.Req", null);
    orgMgt.setTaskOutMessage("MM","NotifyTaxiBooking","notifyTaxiBooking","String:content","String");
    // Role SC
    orgMgt.addTask("SC","PayTX","SC-TX.sendTaxiInvoice.Req","SC-TX.sendTaxiInvoice.Res");
    orgMgt.setTaskOutMessage("SC","PayTX","payTX","String:content","String");
    orgMgt.setTaskInMessage("SC","PayTX","payTX","String:content","String");
    orgMgt.updateTask("SC","Analyze","outputs","add","SC-TX.orderTaxi.Req");

    // contract-level changes
    orgMgt.addContract("SC-TX","SC","TX");
    orgMgt.addTerm("SC-TX","orderTaxi","AtoB");
    orgMgt.setTermOperation("SC-TX","orderTaxi","orderTaxi","String:content","String");
    orgMgt.addTerm("SC-TX","sendTaxiInvoice","BtoA");
    orgMgt.setTermOperation("SC-TX","sendTaxiInvoice","sendTaxiInvoice","String:content","String");
    orgMgt.addContract("TX-MM","TX","MM");
    orgMgt.addTerm("TX-MM","notifyTaxiBooking","AtoB");
    orgMgt.setTermOperation("TX-MM","notifyTaxiBooking","notifyTaxiBooking","String:content","String");

    // behaviour unit changes
    orgMgt.addBehaviorUnit("bHiringTaxi");
    orgMgt.addTaskToBehaviorUnit("bHiringTaxi","TX.OrderTaxi","eOrderTaxiReqd","eOrderedTaxi * eNotifyTaxiBookingReqd");
    orgMgt.addTaskToBehaviorUnit("bHiringTaxi","MM.NotifyTaxiBooking","eNotifyTaxiBookingReqd",null);
    orgMgt.addTaskToBehaviorUnit("bHiringTaxi","TX.ProvideTaxiInvoice",null,"ePayTXReqd");
    orgMgt.addTaskToBehaviorUnit("bHiringTaxi","SC.PayTX","ePayTXReqd","eTXPaid");

    orgMgt.removeBehaviorUnitFromProcess("EuroCars","EuroCarsP1","bRentingVehicle");
    orgMgt.addBehaviorUnitToProcess("EuroCars","EuroCarsP1","bHiringTaxi");
    orgMgt.updateProcessOfVSN("EuroCars","EuroCarsP1","CoT","eMMNotify * eTXPaid");

    System.out.println("Organizational management policy addhire_org has been executed successfully.");
    $mps.setState("enacted");
end