global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "es7_org_remove_stage1"
  when
  $mpsOrg : ManagementPolicyState(id =="es7_org_remove", state=="incipient") and
  ( $mpsOpr : ManagementPolicyState (id=="es7_opr_remove", state=="quiescence"))
  then
   disabledSet.disable("es7_org_remove_stage1");
   System.out.println("Organizational management policy es7_org_remove_stage1 has been started.");

   orgMgt.updateRole("LF","state","passive");
   orgMgt.updateContract("LF-TC2","state","passive");
   orgMgt.updateContract("SC-LF","state","passive");
   orgMgt.updateBehaviorUnit("LegalAssistance","state","passive");
   orgMgt.removeBehaviorUnitFromProcess("HappyTours","HappyToursP1","LegalAssistance");

   orgMgt.removeTaskFromBehaviorUnit("LegalAssistance","LF.InspectAccident");
   orgMgt.removeTaskFromBehaviorUnit("LegalAssistance","SC.PayLF");
   orgMgt.removeBehaviorUnit("LegalAssistance");
 
   orgMgt.removeTerm("LF-TC2","authorizeTow");
   orgMgt.removeContract("LF-TC2");

   orgMgt.removeTerm("SC-LF","inspectAccident");
   orgMgt.removeTerm("SC-LF","payLegalAid");
   orgMgt.removeContract("SC-LF");   
   
   orgMgt.removeTask("LF","InspectAccident");
   orgMgt.removeRole("LF");
   orgMgt.removeTask("SC","PayLF");

   orgMgt.updateTask("TC2","Tow","remove","inputs","LF-TC2.authorizeTow.Req");
   orgMgt.updateTask("SC","Analyze","remove","outputs","GC1-PS.orderParts.Req");

   orgMgt.updateTaskOfBehaviorUnit("TowingByTomTow","TC2.Tow","preEP"," eTowReqd * eGCLocKnown");
   orgMgt.updateTaskOfBehaviorUnit("RepairingByMacRepair","GC1.AssessRepair"," postEP ","eRepairAssessmentReq");

   System.out.println("Organizational management policy es7_org_remove_stage1 has been completed successfully.");
   $mpsOrg.setState("stage1done");
end