global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier
import au.edu.swin.ict.road.common.StatWriter;

rule "bikerental_org_remove_stage1"
  when
  $mpsOrg : ManagementPolicyState(id =="bikerental_org_remove", state=="incipient")
  and  ( $mpsOpr :ManagementPolicyState (id =="bikerental_opr_remove", state=="quiescence"))
  then
   disabledSet.disable("bikerental_org_remove_stage1");
   System.out.println("Organizational management policy bikerental_org_remove_stage1 has been started.");
   
   orgMgt.updateRole("TX","state","passive");
   orgMgt.updateContract("TX-MM","state","passive");
   orgMgt.updateContract("SC-TX","state","passive");
   orgMgt.updateBehaviorUnit("HiringTaxi","state","passive");

   orgMgt.removeBehaviorUnitFromProcess("HappyTours","HappyToursP1","HiringTaxi");
   orgMgt.removeTaskFromBehaviorUnit("HiringTaxi","TX.OrderTaxi");
   orgMgt.removeTaskFromBehaviorUnit("HiringTaxi","MM.NotifyTaxiBooking");
   orgMgt.removeTaskFromBehaviorUnit("HiringTaxi","SC.PayTX");
   orgMgt.removeBehaviorUnit("HiringTaxi");

   orgMgt.removeTerm("SC-TX","orderTaxi");
   orgMgt.removeTerm("SC-TX","sendTaxiInvoice");
   orgMgt.removeContract("SC-TX");

   orgMgt.removeTerm("TX-MM","notifyTaxiBooking");
   orgMgt.removeContract("TX-MM");

   orgMgt.removeTask("TX","OrderTaxi");
   orgMgt.removeTask("TX","ProvideTaxiInvoice");
   orgMgt.removeRole("TX");

   orgMgt.removeTask("SC","PayTX");
   orgMgt.updateTask("SC","Analyze","remove","outputs","SC-TX.orderTax.Req");

   orgMgt.updateTaskOfBehaviorUnit("cuCaseHandling","SC.Analyze","postEP"," eTowReqd * eGCLocKnown * eTowAuthorized * eRentVehicleReqd * eRentVehicleReqd");

   System.out.println("Organizational management policy bikerental_org_remove_stage1 has been completed successfully.");
   StatWriter.writeResTime("MGTR",System.currentTimeMillis());
   $mpsOrg.setState("stage1done");
end