global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;

rule "ChangesForC1-fun-remove"
  when
    $mps : ManagementPolicyState(id =="remove",state=="incipient")
  then
    $mps.setState("active");
    long start1 = System.nanoTime();
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","ruReimbursement");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("EuroCars","EuroCarsP1","ruReimbursement");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("AnyTrucks","AnyTrucksP1","ruReimbursement");

    orgMgt.removeTask("SC","Reimburse");
    orgMgt.removeTask("MM","RequestReimburse");
    orgMgt.removeTask("MM","NotifyReimburseStatus");

    orgMgt.removeTerm("SC-MM","reimburse");
    orgMgt.removeTerm("SC-MM","notifyReimburseStatus");

    orgMgt.removeBehaviorUnit("bReimbursement");

    orgMgt.removeBehaviorUnitFromProcess("HappyTours","HappyToursP1","bReimbursement");
    orgMgt.removeBehaviorUnitFromProcess("EuroCars","EuroCarsP1","bReimbursement");
    orgMgt.removeBehaviorUnitFromProcess("AnyTrucks","AnyTrucksP1","bReimbursement");
    orgMgt.removeBehaviorUnitFromProcess("AnyTrucks","AnyTrucksP2","bReimbursement");

//    System.out.println("Organizational management policy has been executed successfully.");

    oprMgt.removeSynchronizationRule("MM","notifyReimburseStatus");
    oprMgt.removeSynchronizationRule("SC","reimburse");

    oprMgt.removeRoutingRule("SC","reimburseResponse");
    oprMgt.removeRoutingRule("SC","requestReimburse");

    oprMgt.removePassthroughRule("SC-MM","reimburse");
    oprMgt.removePassthroughRule("SC-MM","notifyReimburseStatus");

    oprMgt.removeRegulationUnit("ruReimbursement");
    long stop1 = System.nanoTime();
    System.out.println("Remove : " + (stop1 - start1)/1000000 );
end