global au.edu.swin.ict.road.common.IOrganiserRole orgMgt;
global au.edu.swin.ict.road.common.IOperationalManagerRole oprMgt;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.ManagementPolicyState;
import au.edu.swin.ict.road.common.Classifier;
import au.edu.swin.ict.road.common.RegulationUnitKeyManagementState
import au.edu.swin.ict.road.common.StatWriter;

rule "es9_opr_remove_stage1"
  when
    $mpsOpr : ManagementPolicyState (id =="es9_opr_remove", state=="incipient")
  then
    disabledSet.disable("es9_opr_remove_stage1");
    StatWriter.writeResTime("MGTR",System.currentTimeMillis());
    System.out.println("Operational management policy es9_opr_remove_stage1 has been started.");

    oprMgt.updateRegulationUnitOfProcessRegulationPolicy("HappyTours","HappyToursP1","RentingVehicle","state","passive");
    oprMgt.updateRegulationUnit("RentingVehicle","state","passive");
    oprMgt.removeRegulationUnitsFromProcessRegulationPolicy("HappyTours","HappyToursP1","RentingVehicle");

    oprMgt.removeSynchronizationRulesFromRegulationUnit("RentingVehicle","rentVehicle:VC,endVehicleRent:VC,payVC:SC");
    oprMgt.removeRoutingRulesFromRegulationUnit("RentingVehicle","payVCResponse:SC,rentVehicleResponse:VC,endVehicleRentResponse:VC");
    oprMgt.removePassthroughRulesFromRegulationUnit("RentingVehicle","rentVehicle:SC-VC,rentVehicleResponse:SC-VC,endVehicleRent:SC-VC,endVehicleRentResponse:SC-VC,payVehicleRent:SC-VC,payVehicleRentResponse:SC-VC");
    oprMgt.removeRegulationUnit("RentingVehicle");

    oprMgt.removeSynchronizationRule("VC","rentVehicle,endVehicleRent");
    oprMgt.removeSynchronizationRule("SC","payVC");

    oprMgt.removeRoutingRule("VC","rentVehicleResponse,endVehicleRentResponse");
    oprMgt.updateRoutingRule("SC","analyzeResponse,payGCResponse","replace","SC_Routing_Diff_Replace_V2.drl");
    oprMgt.removeRoutingRule("SC","payVCResponse");

    oprMgt.removePassthroughRule("SC-VC","rentVehicle,rentVehicleResponse,endVehicleRent,endVehicleRentResponse,payVehicleRent,payVehicleRentResponse");
    oprMgt.updateGlobalRule("terminateV1","replace" ,"roadside_global_diff_replace_V2.drl");

    System.out.println("Operational management policy es9_opr_remove_stage1 has been completed successfully.");
    $mpsOpr.setState("quiescence");
end