global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "receiveExternalAssessmentResponse"
  when
   $msg : RoleServiceMessage(operationName== "receiveExternalAssessmentResponse", state=="forwardable")
  then
   actions.Forward("GC1-PS.orderParts.Req","OrderPartsReq.xsl",$msg);
end